"""content_concepts.py — Part 0 · Concepts (How it works) of the slm-lab walk-through.

A code-free conceptual tour. It REUSES the diagrams authored in content.py (imported
below, byte-for-byte) and the most-iterated callouts, with tightened connective prose.
The runnable code lives in Part 1 (content.py); this page links across to it.

build.py renders this to site/ideas/index.html.
"""

from content import (  # diagrams + the Python primer live in content.py
    LANDSCAPE_SVG, CYCLE_SVG, LINEAR_SVG, EMBED_SCATTER_SVG, EMBED_HEATMAP_SVG,
)

META = {
    "title": "How a language model works: the ideas",
    "subtitle": "Part 0 · Concepts: the plain-English principles behind the build, no code.",
}

HERO = r"""
<p class="kicker">slm-lab · Part 0 · Concepts</p>
<h1>How a language model works</h1>
<p class="lede">The ideas, in plain English, with no code: what a language model actually <em>is</em>,
how text becomes numbers, what &ldquo;learning&rdquo; means, and how the pieces fit. Read this first;
then <a href="../track-a/">Part 1</a> builds every one of these ideas in real, runnable code, and
<a href="../track-b/">Part 2</a> fine-tunes a real model into a useful expert.</p>

<div class="bigidea">
  <p><strong>The whole thing in one breath:</strong> a language model is a <strong>mathematical
  function</strong> with millions of adjustable numbers (its <strong>parameters</strong>) that, given
  some text so far, predicts what comes next. <em>Training</em> tunes those numbers (millions of tiny
  nudges) until coherent language falls out. <em>Generation</em> runs the function in a loop to write.</p>
  <p>Everything below unpacks that: how text becomes numbers, how the model &ldquo;looks back&rdquo; at
  what it has read, how it measures its own mistakes, and how it slowly improves.</p>
</div>

<p class="readnote"><strong>No Python here.</strong> This page is concepts and pictures only. Every idea
reappears as real code in <a href="../track-a/">Part 1 · Pre-training</a>; each section links across to
where it's built.</p>
"""


# ---- Part-0-only diagrams (hand-styled inline SVG; data notes in each caption) ----
# Real numbers throughout: char ids from notebook 01's vocabulary, BPE ids from
# notebook 02's committed output, probabilities computed from the trained v2
# checkpoint. SURFACE3D_SVG is generated by gen_loss_surface.py (real gradient
# descent on the drawn surface) -- rerun it and repaste to tweak.

TOKENIZE_SVG = r'''<svg viewBox="0 0 720 470" role="img" aria-label="Tokenization: the sentence Once upon a time as 16 per-character numbers (notebook 01), as 4 BPE word-chunks with their real token ids (notebook 02), and three words showing how frequency sets chunk size: butterfly is one chunk, thunderstorm two, unbelievable five.">
<text x="30" y="26" font-size="13" font-weight="700" fill="#1c2230">① One number per <tspan fill="#3253d6">character</tspan> — how the from-scratch model (notebook 01) reads</text>
<rect x="30" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="50.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">O</text>
<text x="50.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">36</text>
<rect x="72" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="92.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">n</text>
<text x="92.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">61</text>
<rect x="114" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="134.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">c</text>
<text x="134.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">50</text>
<rect x="156" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="176.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">e</text>
<text x="176.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">52</text>
<rect x="198" y="42" width="40" height="32" rx="6" fill="#f1f3f8" stroke="#b9c2d6" stroke-width="1.2"/>
<text x="218.0" y="63" text-anchor="middle" font-size="14" fill="#8a93a3" font-family="ui-monospace,Menlo,monospace">␣</text>
<text x="218.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">1</text>
<rect x="240" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="260.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">u</text>
<text x="260.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">68</text>
<rect x="282" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="302.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">p</text>
<text x="302.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">63</text>
<rect x="324" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="344.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">o</text>
<text x="344.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">62</text>
<rect x="366" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="386.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">n</text>
<text x="386.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">61</text>
<rect x="408" y="42" width="40" height="32" rx="6" fill="#f1f3f8" stroke="#b9c2d6" stroke-width="1.2"/>
<text x="428.0" y="63" text-anchor="middle" font-size="14" fill="#8a93a3" font-family="ui-monospace,Menlo,monospace">␣</text>
<text x="428.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">1</text>
<rect x="450" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="470.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">a</text>
<text x="470.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">48</text>
<rect x="492" y="42" width="40" height="32" rx="6" fill="#f1f3f8" stroke="#b9c2d6" stroke-width="1.2"/>
<text x="512.0" y="63" text-anchor="middle" font-size="14" fill="#8a93a3" font-family="ui-monospace,Menlo,monospace">␣</text>
<text x="512.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">1</text>
<rect x="534" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="554.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">t</text>
<text x="554.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">67</text>
<rect x="576" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="596.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">i</text>
<text x="596.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">56</text>
<rect x="618" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="638.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">m</text>
<text x="638.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">60</text>
<rect x="660" y="42" width="40" height="32" rx="6" fill="#eef2ff" stroke="#3253d6" stroke-width="1.2"/>
<text x="680.0" y="63" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">e</text>
<text x="680.0" y="92" text-anchor="middle" font-size="9.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">52</text>
<text x="30" y="124" font-size="10.5" fill="#5a6373">16 characters → 16 numbers. The model must learn spelling before it can learn anything else.</text>
<line x1="30" y1="140" x2="690" y2="140" stroke="#e4e7ee" stroke-width="1.5"/>
<text x="30" y="166" font-size="13" font-weight="700" fill="#1c2230">② One number per <tspan fill="#3253d6">word-chunk</tspan> (BPE) — how the tuned model (notebook 02) reads</text>
<rect x="97" y="182" width="140" height="40" rx="8" fill="#eef2ff" stroke="#3253d6" stroke-width="1.6"/>
<text x="167" y="208" text-anchor="middle" font-size="16" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">␣Once</text>
<text x="167" y="240" text-anchor="middle" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">#5404</text>
<rect x="247" y="182" width="140" height="40" rx="8" fill="#e7f6f0" stroke="#0e7a5f" stroke-width="1.6"/>
<text x="317" y="208" text-anchor="middle" font-size="16" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">␣upon</text>
<text x="317" y="240" text-anchor="middle" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">#288</text>
<rect x="397" y="182" width="76" height="40" rx="8" fill="#fbf1e0" stroke="#b5731a" stroke-width="1.6"/>
<text x="435" y="208" text-anchor="middle" font-size="16" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">␣a</text>
<text x="435" y="240" text-anchor="middle" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">#107</text>
<rect x="483" y="182" width="140" height="40" rx="8" fill="#f1ecfb" stroke="#5a3aa6" stroke-width="1.6"/>
<text x="553" y="208" text-anchor="middle" font-size="16" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">␣time</text>
<text x="553" y="240" text-anchor="middle" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">#244</text>
<text x="30" y="276" font-size="10.5" fill="#5a6373">Same text: 4 numbers instead of 16 (␣ marks the space each chunk carries). The model now reasons over meaningful pieces,</text>
<text x="30" y="292" font-size="10.5" fill="#5a6373">and the same context window holds ~4× more story — most of the v1 → v2 quality leap in Part 1.</text>
<line x1="30" y1="308" x2="690" y2="308" stroke="#e4e7ee" stroke-width="1.5"/>
<text x="30" y="334" font-size="13" font-weight="700" fill="#1c2230">③ How big is a chunk? <tspan fill="#3253d6">Frequency</tspan> decides — the same tokenizer, three words</text>
<rect x="30" y="350" width="123" height="36" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.5"/>
<text x="92" y="373" text-anchor="middle" font-size="13.5" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">␣butterfly</text>
<text x="92" y="406" text-anchor="middle" font-size="9.5" fill="#5a6373">1 chunk — the stories used it constantly</text>
<rect x="182" y="350" width="102" height="36" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.5"/>
<text x="233" y="373" text-anchor="middle" font-size="13.5" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">␣thunder</text>
<rect x="287" y="350" width="70" height="36" rx="7" fill="#e7f6f0" stroke="#0e7a5f" stroke-width="1.5"/>
<text x="322" y="373" text-anchor="middle" font-size="13.5" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">storm</text>
<text x="270" y="406" text-anchor="middle" font-size="9.5" fill="#5a6373">2 chunks — both meaningful</text>
<rect x="386" y="350" width="50" height="36" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.5"/>
<text x="411" y="373" text-anchor="middle" font-size="13.5" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">␣un</text>
<rect x="439" y="350" width="50" height="36" rx="7" fill="#e7f6f0" stroke="#0e7a5f" stroke-width="1.5"/>
<text x="464" y="373" text-anchor="middle" font-size="13.5" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">bel</text>
<rect x="492" y="350" width="39" height="36" rx="7" fill="#fbf1e0" stroke="#b5731a" stroke-width="1.5"/>
<text x="511" y="373" text-anchor="middle" font-size="13.5" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">ie</text>
<rect x="534" y="350" width="28" height="36" rx="7" fill="#f1ecfb" stroke="#5a3aa6" stroke-width="1.5"/>
<text x="548" y="373" text-anchor="middle" font-size="13.5" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">v</text>
<rect x="565" y="350" width="60" height="36" rx="7" fill="#fbecf3" stroke="#a8386a" stroke-width="1.5"/>
<text x="595" y="373" text-anchor="middle" font-size="13.5" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">able</text>
<text x="506" y="406" text-anchor="middle" font-size="9.5" fill="#5a6373">5 chunks — rare, spelled from pieces</text>
<text x="30" y="438" font-size="10.5" fill="#5a6373">Words the training text used constantly earn a chunk of their own; rarer ones are spelled out of reusable pieces — and the</text>
<text x="30" y="454" font-size="10.5" fill="#5a6373">pieces themselves often carry meaning (␣thunder, storm, ␣un…, …able). Nothing is ever out-of-vocabulary.</text>
</svg>'''

EMBED_LOOKUP_SVG = r'''<svg viewBox="0 0 720 318" role="img" aria-label="The embedding lookup: each token id indexes a row of the embedding table; fox, cat and dog get similar columns of numbers, the gets a different one.">
<text x="360" y="24" text-anchor="middle" font-size="12.5" font-weight="700" fill="#1c2230">A token’s ID indexes the embedding table: row #ID <tspan fill="#3253d6">is</tspan> its vector</text>
<defs><marker id="arK" markerWidth="8" markerHeight="8" refX="5" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 Z" fill="#5a6373"/></marker></defs>
<rect x="76" y="40" width="88" height="30" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.4"/>
<text x="120" y="60" text-anchor="middle" font-size="13.5" font-weight="700" fill="#1c2230">fox</text>
<text x="120" y="86" text-anchor="middle" font-size="10" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">ID #1234</text>
<line x1="120" y1="92" x2="120" y2="112" stroke="#5a6373" stroke-width="1.4" marker-end="url(#arK)"/>
<text x="128" y="107" font-size="9" fill="#8a93a3">row #1234</text>
<rect x="88" y="118" width="64" height="27" fill="rgb(246,206,206)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="120" y="136" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">0.31</text>
<rect x="88" y="145" width="64" height="27" fill="rgb(64,108,206)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="120" y="163" text-anchor="middle" font-size="11" fill="#ffffff" font-family="ui-monospace,Menlo,monospace">-1.20</text>
<rect x="88" y="172" width="64" height="27" fill="rgb(253,247,247)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="120" y="190" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">0.05</text>
<rect x="88" y="199" width="64" height="27" fill="#fbfbfd" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="120" y="217" text-anchor="middle" font-size="11" fill="#5a6373">⋮</text>
<text x="120" y="243" text-anchor="middle" font-size="9" fill="#8a93a3">256 numbers</text>
<rect x="236" y="40" width="88" height="30" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.4"/>
<text x="280" y="60" text-anchor="middle" font-size="13.5" font-weight="700" fill="#1c2230">cat</text>
<text x="280" y="86" text-anchor="middle" font-size="10" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">ID #882</text>
<line x1="280" y1="92" x2="280" y2="112" stroke="#5a6373" stroke-width="1.4" marker-end="url(#arK)"/>
<text x="288" y="107" font-size="9" fill="#8a93a3">row #882</text>
<rect x="248" y="118" width="64" height="27" fill="rgb(246,210,210)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="280" y="136" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">0.28</text>
<rect x="248" y="145" width="64" height="27" fill="rgb(88,127,212)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="280" y="163" text-anchor="middle" font-size="11" fill="#ffffff" font-family="ui-monospace,Menlo,monospace">-1.05</text>
<rect x="248" y="172" width="64" height="27" fill="rgb(251,236,236)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="280" y="190" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">0.12</text>
<rect x="248" y="199" width="64" height="27" fill="#fbfbfd" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="280" y="217" text-anchor="middle" font-size="11" fill="#5a6373">⋮</text>
<text x="280" y="243" text-anchor="middle" font-size="9" fill="#8a93a3">256 numbers</text>
<rect x="396" y="40" width="88" height="30" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.4"/>
<text x="440" y="60" text-anchor="middle" font-size="13.5" font-weight="700" fill="#1c2230">dog</text>
<text x="440" y="86" text-anchor="middle" font-size="10" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">ID #905</text>
<line x1="440" y1="92" x2="440" y2="112" stroke="#5a6373" stroke-width="1.4" marker-end="url(#arK)"/>
<text x="448" y="107" font-size="9" fill="#8a93a3">row #905</text>
<rect x="408" y="118" width="64" height="27" fill="rgb(244,199,199)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="440" y="136" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">0.35</text>
<rect x="408" y="145" width="64" height="27" fill="rgb(46,95,202)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="440" y="163" text-anchor="middle" font-size="11" fill="#ffffff" font-family="ui-monospace,Menlo,monospace">-1.31</text>
<rect x="408" y="172" width="64" height="27" fill="rgb(252,253,254)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="440" y="190" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">-0.02</text>
<rect x="408" y="199" width="64" height="27" fill="#fbfbfd" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="440" y="217" text-anchor="middle" font-size="11" fill="#5a6373">⋮</text>
<text x="440" y="243" text-anchor="middle" font-size="9" fill="#8a93a3">256 numbers</text>
<rect x="556" y="40" width="88" height="30" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.4"/>
<text x="600" y="60" text-anchor="middle" font-size="13.5" font-weight="700" fill="#1c2230">the</text>
<text x="600" y="86" text-anchor="middle" font-size="10" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">ID #14</text>
<line x1="600" y1="92" x2="600" y2="112" stroke="#5a6373" stroke-width="1.4" marker-end="url(#arK)"/>
<text x="608" y="107" font-size="9" fill="#8a93a3">row #14</text>
<rect x="568" y="118" width="64" height="27" fill="rgb(108,143,218)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="600" y="136" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">-0.92</text>
<rect x="568" y="145" width="64" height="27" fill="rgb(242,185,185)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="600" y="163" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">0.44</text>
<rect x="568" y="172" width="64" height="27" fill="rgb(158,180,230)" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="600" y="190" text-anchor="middle" font-size="11" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">-0.61</text>
<rect x="568" y="199" width="64" height="27" fill="#fbfbfd" stroke="#e4e7ee" stroke-width="0.8"/>
<text x="600" y="217" text-anchor="middle" font-size="11" fill="#5a6373">⋮</text>
<text x="600" y="243" text-anchor="middle" font-size="9" fill="#8a93a3">256 numbers</text>
<text x="240" y="296" text-anchor="middle" font-size="11" font-weight="700" fill="#1c2230">fox · cat · dog → similar rows (similar meaning)</text>
<text x="600" y="296" text-anchor="middle" font-size="11" font-weight="700" fill="#1c2230">“the” → different</text>
</svg>'''

PROBS_SVG = r'''<svg viewBox="0 0 720 286" role="img" aria-label="The model's real next-word scores for the prompt One day, Lily went to the: park 64 percent, store 11 percent, then small scores, with about 20 percent spread over all other chunks.">
<text x="30" y="26" font-size="14" font-weight="700" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">“One day, Lily went to the ___”</text>
<text x="30" y="46" font-size="11" fill="#5a6373">the model’s scores for what comes next — its real output, one number per vocabulary chunk</text>
<text x="218" y="79" text-anchor="end" font-size="12" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> park</text>
<rect x="228" y="64" width="380" height="21" rx="4" fill="#3253d6"/>
<text x="616" y="79" font-size="11" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">63.7%</text>
<text x="218" y="109" text-anchor="end" font-size="12" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> store</text>
<rect x="228" y="94" width="66" height="21" rx="4" fill="#3253d6"/>
<text x="302" y="109" font-size="11" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">11.0%</text>
<text x="218" y="139" text-anchor="end" font-size="12" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> market</text>
<rect x="228" y="124" width="11" height="21" rx="4" fill="#3253d6"/>
<text x="247" y="139" font-size="11" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">1.9%</text>
<text x="218" y="169" text-anchor="end" font-size="12" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> beach</text>
<rect x="228" y="154" width="11" height="21" rx="4" fill="#3253d6"/>
<text x="247" y="169" font-size="11" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">1.9%</text>
<text x="218" y="199" text-anchor="end" font-size="12" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> zoo</text>
<rect x="228" y="184" width="10" height="21" rx="4" fill="#3253d6"/>
<text x="246" y="199" font-size="11" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">1.6%</text>
<text x="218" y="229" text-anchor="end" font-size="12" font-style="italic" fill="#5a6373">everything else (~8,000 chunks)</text>
<rect x="228" y="214" width="119" height="21" rx="4" fill="#b9c2d6"/>
<text x="355" y="229" font-size="11" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">19.9%</text>
<text x="30" y="266" font-size="10.5" fill="#5a6373">The scores sum to 100% across all 8,192 chunks. Training (§7) nudges the weights so the chunk that actually came next</text>
<text x="30" y="282" font-size="10.5" fill="#5a6373">gets a bigger share; generating (§8) means picking from this menu, appending, and scoring again.</text>
</svg>'''

ATTENTION_SVG = r'''<svg viewBox="0 0 720 312" role="img" aria-label="Attention, measured: arcs from the word it back to earlier words in the sentence The dragon looked at the boy and it. The arc to dragon carries 76 percent of the attention; small arcs go to The, and, and boy; it keeps 8 percent for itself.">
<text x="360" y="26" text-anchor="middle" font-size="13.5" font-weight="700" fill="#1c2230">Where does <tspan font-family="ui-monospace,Menlo,monospace" fill="#b5731a">it</tspan> look? — one real attention head, measured</text>
<text x="360" y="44" text-anchor="middle" font-size="11" fill="#5a6373">the trained Part 1 model, layer 2 of 6, head 4 of 6 — each arc’s thickness = how much of the blend</text>
<path d="M 581 204 Q 362 -25 144 204" fill="none" stroke="#3253d6" stroke-width="1.9" opacity="0.40"/>
<text x="362" y="81" text-anchor="middle" font-size="10" font-weight="400" fill="#3253d6">7%</text>
<path d="M 581 204 Q 398 0 215 204" fill="none" stroke="#e8462e" stroke-width="8.8" opacity="0.84"/>
<text x="398" y="94" text-anchor="middle" font-size="11" font-weight="700" fill="#e8462e">76%</text>
<path d="M 581 204 Q 441 31 301 204" fill="none" stroke="#3253d6" stroke-width="1.3" opacity="0.36"/>
<path d="M 581 204 Q 528 93 474 204" fill="none" stroke="#3253d6" stroke-width="1.4" opacity="0.36"/>
<text x="528" y="141" text-anchor="middle" font-size="10" font-weight="400" fill="#3253d6">2%</text>
<path d="M 581 204 Q 556 114 530 204" fill="none" stroke="#3253d6" stroke-width="1.8" opacity="0.39"/>
<text x="556" y="151" text-anchor="middle" font-size="10" font-weight="400" fill="#3253d6">6%</text>
<rect x="120" y="208" width="48" height="34" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.3"/>
<text x="144" y="230" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">The</text>
<rect x="176" y="208" width="78" height="34" rx="7" fill="#fbecf3" stroke="#a8386a" stroke-width="2.2"/>
<text x="215" y="230" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">dragon</text>
<rect x="262" y="208" width="78" height="34" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.3"/>
<text x="301" y="230" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">looked</text>
<rect x="348" y="208" width="38" height="34" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.3"/>
<text x="367" y="230" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">at</text>
<rect x="394" y="208" width="48" height="34" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.3"/>
<text x="418" y="230" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">the</text>
<rect x="450" y="208" width="48" height="34" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.3"/>
<text x="474" y="230" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">boy</text>
<rect x="506" y="208" width="48" height="34" rx="7" fill="#eef2ff" stroke="#3253d6" stroke-width="1.3"/>
<text x="530" y="230" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">and</text>
<rect x="562" y="208" width="38" height="34" rx="7" fill="#fbf1e0" stroke="#b5731a" stroke-width="2.2"/>
<text x="581" y="230" text-anchor="middle" font-size="14" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">it</text>
<text x="581" y="260" text-anchor="middle" font-size="9.5" fill="#b5731a">the token asking (its “query”) — keeps 8% for itself</text>
<text x="215" y="260" text-anchor="middle" font-size="9.5" fill="#a8386a">the best-matching “key”</text>
<text x="30" y="292" font-size="10.5" fill="#5a6373">“looked”, “at”, “the” get ≈0–1%. This head has learned to track who the sentence is about; other heads in the same</text>
<text x="30" y="308" font-size="10.5" fill="#5a6373">model attend to different things (recent words, sentence starts) — together they give the next layer rich context.</text>
</svg>'''

TEMP_SVG = r'''<svg viewBox="0 0 720 320" role="img" aria-label="The same real next-word scores for Tom was very, sampled at temperature 0.5 and 1.1. At 0.5 happy dominates; at 1.1 nearly half the probability spreads to the long tail of other chunks.">
<text x="360" y="24" text-anchor="middle" font-size="13" font-weight="700" fill="#1c2230" font-family="ui-monospace,Menlo,monospace">“Tom was very ___”</text>
<text x="360" y="42" text-anchor="middle" font-size="11" fill="#5a6373">same model, same scores — only the sampling temperature changes</text>
<text x="187" y="68" text-anchor="middle" font-size="12" font-weight="700" fill="#0e7a5f">temperature 0.5 — plays it safe</text>
<text x="148" y="96" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> happy</text>
<rect x="156" y="82" width="150" height="19" rx="4" fill="#0e7a5f"/>
<text x="313" y="96" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">58.7%</text>
<text x="148" y="124" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> sad</text>
<rect x="156" y="110" width="60" height="19" rx="4" fill="#0e7a5f"/>
<text x="223" y="124" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">23.3%</text>
<text x="148" y="152" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> excited</text>
<rect x="156" y="138" width="26" height="19" rx="4" fill="#0e7a5f"/>
<text x="189" y="152" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">10.3%</text>
<text x="148" y="180" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> scared</text>
<rect x="156" y="166" width="6" height="19" rx="4" fill="#0e7a5f"/>
<text x="169" y="180" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">2.3%</text>
<text x="148" y="208" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> angry</text>
<rect x="156" y="194" width="4" height="19" rx="4" fill="#0e7a5f"/>
<text x="167" y="208" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">1.7%</text>
<text x="148" y="236" text-anchor="end" font-size="11.5" font-style="italic" fill="#5a6373">everything else</text>
<rect x="156" y="222" width="7" height="19" rx="4" fill="#b9c2d6"/>
<text x="170" y="236" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">2.8%</text>
<text x="532" y="68" text-anchor="middle" font-size="12" font-weight="700" fill="#9a5b00">temperature 1.1 — adventurous</text>
<text x="493" y="96" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> happy</text>
<rect x="501" y="82" width="52" height="19" rx="4" fill="#b5731a"/>
<text x="560" y="96" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">20.3%</text>
<text x="493" y="124" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> sad</text>
<rect x="501" y="110" width="34" height="19" rx="4" fill="#b5731a"/>
<text x="542" y="124" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">13.4%</text>
<text x="493" y="152" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> excited</text>
<rect x="501" y="138" width="24" height="19" rx="4" fill="#b5731a"/>
<text x="532" y="152" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">9.2%</text>
<text x="493" y="180" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> scared</text>
<rect x="501" y="166" width="12" height="19" rx="4" fill="#b5731a"/>
<text x="520" y="180" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">4.7%</text>
<text x="493" y="208" text-anchor="end" font-size="11.5" font-family="ui-monospace,Menlo,monospace" fill="#1c2230"> angry</text>
<rect x="501" y="194" width="10" height="19" rx="4" fill="#b5731a"/>
<text x="518" y="208" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">4.0%</text>
<text x="493" y="236" text-anchor="end" font-size="11.5" font-style="italic" fill="#5a6373">everything else</text>
<rect x="501" y="222" width="116" height="19" rx="4" fill="#b9c2d6"/>
<text x="624" y="236" font-size="10.5" fill="#5a6373" font-family="ui-monospace,Menlo,monospace">45.4%</text>
<text x="660" y="265" text-anchor="end" font-size="10" fill="#9a5b00" font-style="italic">↑ the long tail gets a real chance</text>
<text x="30" y="294" font-size="10.5" fill="#5a6373">Temperature reshapes how the menu is sampled, not the menu itself: at 0.5, “happy” wins ~59% of draws; at 1.1, nearly half</text>
<text x="30" y="310" font-size="10.5" fill="#5a6373">the draws come from outside the top five — that’s where the surprises (good and bad) come from.</text>
</svg>'''

SURFACE3D_SVG = r'''<svg viewBox="0 0 660 350" role="img" aria-label="A loss surface over two weights, drawn as a 3-D wireframe valley. A ball starts high on one slope and a dotted gradient-descent path of real downhill steps curves to the lowest point of the valley.">
<defs><marker id="arS" markerWidth="8" markerHeight="8" refX="5" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 Z" fill="#e8462e"/></marker></defs>
<polyline points="330.0,-141.3 304.0,-84.2 278.0,-34.8 252.0,6.7 226.0,39.9 200.0,64.7 174.0,80.9 148.0,88.5 122.0,87.6 96.0,78.2 70.0,60.6 44.0,35.0 18.0,1.7" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="356.0,-105.3 330.0,-45.8 304.0,5.9 278.0,49.4 252.0,84.1 226.0,109.9 200.0,126.5 174.0,133.7 148.0,131.8 122.0,120.9 96.0,101.3 70.0,73.4 44.0,37.7" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="382.0,-73.3 356.0,-12.6 330.0,40.3 304.0,84.8 278.0,120.3 252.0,146.6 226.0,163.3 200.0,170.4 174.0,168.0 148.0,156.3 122.0,135.6 96.0,106.6 70.0,69.7" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="408.0,-45.2 382.0,15.3 356.0,68.0 330.0,112.3 304.0,147.7 278.0,173.9 252.0,190.6 226.0,197.8 200.0,195.4 174.0,183.8 148.0,163.3 122.0,134.5 96.0,97.8" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="434.0,-21.2 408.0,37.8 382.0,89.1 356.0,132.1 330.0,166.5 304.0,192.1 278.0,208.6 252.0,215.9 226.0,214.2 200.0,203.6 174.0,184.4 148.0,157.0 122.0,121.8" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="460.0,-1.2 434.0,55.2 408.0,103.9 382.0,144.8 356.0,177.5 330.0,202.0 304.0,218.1 278.0,225.8 252.0,225.2 226.0,216.3 200.0,199.3 174.0,174.4 148.0,141.8" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="486.0,14.5 460.0,67.7 434.0,113.3 408.0,151.5 382.0,182.2 356.0,205.3 330.0,221.0 304.0,229.2 278.0,229.8 252.0,223.0 226.0,208.7 200.0,186.8 174.0,157.5" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="512.0,25.6 486.0,75.6 460.0,118.2 434.0,153.6 408.0,182.2 382.0,204.1 356.0,219.3 330.0,227.9 304.0,229.9 278.0,225.1 252.0,213.5 226.0,194.7 200.0,168.6" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="538.0,31.8 512.0,79.2 486.0,119.3 460.0,152.6 434.0,179.5 408.0,200.2 382.0,215.1 356.0,224.1 330.0,227.1 304.0,224.1 278.0,214.6 252.0,198.3 226.0,174.8" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="564.0,33.0 538.0,78.8 512.0,117.4 486.0,149.5 460.0,175.3 434.0,195.5 408.0,210.1 382.0,219.3 356.0,223.0 330.0,221.0 304.0,212.8 278.0,198.0 252.0,176.0" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="590.0,28.9 564.0,74.6 538.0,113.0 512.0,144.9 486.0,170.7 460.0,190.8 434.0,205.4 408.0,214.6 382.0,218.4 356.0,216.4 330.0,208.4 304.0,193.7 278.0,171.9" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="616.0,19.7 590.0,66.5 564.0,106.2 538.0,139.0 512.0,165.6 486.0,186.2 460.0,200.9 434.0,210.0 408.0,213.3 382.0,210.5 356.0,201.5 330.0,185.7 304.0,162.7" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="642.0,5.3 616.0,54.5 590.0,96.4 564.0,131.3 538.0,159.4 512.0,181.0 486.0,196.1 460.0,204.8 434.0,207.1 408.0,202.8 382.0,191.8 356.0,173.7 330.0,148.3" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="330.0,-141.3 356.0,-105.3 382.0,-73.3 408.0,-45.2 434.0,-21.2 460.0,-1.2 486.0,14.5 512.0,25.6 538.0,31.8 564.0,33.0 590.0,28.9 616.0,19.7 642.0,5.3" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="304.0,-84.2 330.0,-45.8 356.0,-12.6 382.0,15.3 408.0,37.8 434.0,55.2 460.0,67.7 486.0,75.6 512.0,79.2 538.0,78.8 564.0,74.6 590.0,66.5 616.0,54.5" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="278.0,-34.8 304.0,5.9 330.0,40.3 356.0,68.0 382.0,89.1 408.0,103.9 434.0,113.3 460.0,118.2 486.0,119.3 512.0,117.4 538.0,113.0 564.0,106.2 590.0,96.4" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="252.0,6.7 278.0,49.4 304.0,84.8 330.0,112.3 356.0,132.1 382.0,144.8 408.0,151.5 434.0,153.6 460.0,152.6 486.0,149.5 512.0,144.9 538.0,139.0 564.0,131.3" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="226.0,39.9 252.0,84.1 278.0,120.3 304.0,147.7 330.0,166.5 356.0,177.5 382.0,182.2 408.0,182.2 434.0,179.5 460.0,175.3 486.0,170.7 512.0,165.6 538.0,159.4" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="200.0,64.7 226.0,109.9 252.0,146.6 278.0,173.9 304.0,192.1 330.0,202.0 356.0,205.3 382.0,204.1 408.0,200.2 434.0,195.5 460.0,190.8 486.0,186.2 512.0,181.0" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="174.0,80.9 200.0,126.5 226.0,163.3 252.0,190.6 278.0,208.6 304.0,218.1 330.0,221.0 356.0,219.3 382.0,215.1 408.0,210.1 434.0,205.4 460.0,200.9 486.0,196.1" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="148.0,88.5 174.0,133.7 200.0,170.4 226.0,197.8 252.0,215.9 278.0,225.8 304.0,229.2 330.0,227.9 356.0,224.1 382.0,219.3 408.0,214.6 434.0,210.0 460.0,204.8" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="122.0,87.6 148.0,131.8 174.0,168.0 200.0,195.4 226.0,214.2 252.0,225.2 278.0,229.8 304.0,229.9 330.0,227.1 356.0,223.0 382.0,218.4 408.0,213.3 434.0,207.1" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="96.0,78.2 122.0,120.9 148.0,156.3 174.0,183.8 200.0,203.6 226.0,216.3 252.0,223.0 278.0,225.1 304.0,224.1 330.0,221.0 356.0,216.4 382.0,210.5 408.0,202.8" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="70.0,60.6 96.0,101.3 122.0,135.6 148.0,163.3 174.0,184.4 200.0,199.3 226.0,208.7 252.0,213.5 278.0,214.6 304.0,212.8 330.0,208.4 356.0,201.5 382.0,191.8" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="44.0,35.0 70.0,73.4 96.0,106.6 122.0,134.5 148.0,157.0 174.0,174.4 200.0,186.8 226.0,194.7 252.0,198.3 278.0,198.0 304.0,193.7 330.0,185.7 356.0,173.7" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="18.0,1.7 44.0,37.7 70.0,69.7 96.0,97.8 122.0,121.8 148.0,141.8 174.0,157.5 200.0,168.6 226.0,174.8 252.0,176.0 278.0,171.9 304.0,162.7 330.0,148.3" fill="none" stroke="#b9c2d6" stroke-width="1" opacity="0.85"/>
<polyline points="64.8,61.7 132.2,136.5 184.3,178.6 219.8,197.2 242.4,204.5 256.7,207.2 265.8,208.3 271.6,208.7 275.5,208.9 278.0,209.0 279.6,209.0 280.7,209.1 281.5,209.1 282.0,209.1" fill="none" stroke="#e8462e" stroke-width="2.4" stroke-dasharray="6 4" marker-end="url(#arS)"/>
<circle cx="132.2" cy="136.5" r="2.6" fill="#e8462e"/>
<circle cx="219.8" cy="197.2" r="2.6" fill="#e8462e"/>
<circle cx="256.7" cy="207.2" r="2.6" fill="#e8462e"/>
<circle cx="271.6" cy="208.7" r="2.6" fill="#e8462e"/>
<circle cx="278.0" cy="209.0" r="2.6" fill="#e8462e"/>
<circle cx="280.7" cy="209.1" r="2.6" fill="#e8462e"/>
<circle cx="64.8" cy="61.7" r="9" fill="#e8462e" stroke="#fff" stroke-width="2.5"/>
<text x="81" y="50" font-size="12" fill="#1c2230">start: random weights</text>
<circle cx="282.0" cy="209.1" r="5" fill="#0e7a5f" stroke="#fff" stroke-width="1.8"/>
<text x="294" y="227" font-size="12" fill="#0e7a5f">lowest loss</text>
<text x="52" y="210" font-size="12" fill="#5a6373" transform="rotate(-64 52 210)">loss (height) ↑</text>
<text x="470" y="336" font-size="12" fill="#5a6373">weight 1 →</text>
<text x="120" y="336" font-size="12" fill="#5a6373">← weight 2</text>
</svg>'''

SECTIONS = [

{
 "id": "what", "num": "1", "title": "What a model actually does",
 "part": "The idea", "part_banner": "Part 0 · Concepts",
 "blocks": [
  ("prose", r"""
<p>Strip away the mystique and a language model does one narrow thing: <strong>given the text so far,
it predicts what comes next.</strong> Not whole thoughts, just the next small chunk (a <em>token</em>:
a word or word-piece). To write a sentence it just does this over and over, each new token appended and
fed back in. That's it. Everything else is machinery in service of making that one prediction good.</p>
<p>So &ldquo;a model that writes&rdquo; is really a model that <em>scores what's likely next</em>, run in
a loop. The skill isn't generating; it's the prediction underneath. Here is that one prediction,
for real, from the tiny model this lab builds in Part 1:</p>
"""),
  ("diagram", PROBS_SVG,
   "One real prediction from the tiny tuned model this lab builds in Part 1: given the text so far, "
   "it puts a score on every chunk in its vocabulary. “park” isn't a stored fact; it's the "
   "strongest statistical echo of the stories it read."),
  ("callout", "key", "A model is a function, not a mind", r"""
<p>It helps to picture a giant mathematical function: text in → a probability for every possible next
token out. The function's behaviour is fixed by its <strong>parameters</strong>: millions of numbers
set during training. No look-ups of &ldquo;facts,&rdquo; no rules someone wrote, just numbers, multiplied
and added, shaped by training to make good predictions.</p>
"""),
 ],
},

{
 "id": "tokens", "num": "2", "title": "Text becomes numbers (tokens)",
 "blocks": [
  ("prose", r"""
<p>A model can't do arithmetic on letters, so the first move is to turn text into numbers. The text is
chopped into <strong>tokens</strong>: common chunks (whole words like <code>fox</code>, or word-pieces),
each with an integer <strong>ID</strong> (its index in a fixed list called the <em>vocabulary</em>).
&ldquo;fox&rdquo; might be token #1234. That's all a token is to the model: an ID. There's more than one
way to chop, and the choice matters enormously:</p>
"""),
  ("diagram", TOKENIZE_SVG,
   "The same sentence, tokenized two ways — real numbers from Part 1's notebooks (character IDs "
   "from notebook 01, BPE chunk IDs from notebook 02) — and, below, what happens to words the "
   "corpus saw rarely: the same tokenizer splits them into reusable, often meaningful pieces."),
  ("prose", r"""
<p>The reverse runs at the end: the model's predicted ID is mapped back to its chunk of text, and the
pieces are glued together into words. <a href="../track-a/#data">Part 1 builds the tokenizer →</a></p>
"""),
 ],
},

{
 "id": "embed", "num": "3", "title": "Tokens become vectors (embeddings)",
 "blocks": [
  ("prose", r"""
<p>An ID like #1234 carries no <em>meaning</em>: #1235 isn't &ldquo;one more&rdquo; than fox. So each
token is turned into a <strong>list of numbers</strong>, its <strong>embedding</strong> (256 numbers in
our tiny model). Think of those numbers as coordinates that place the token in a vast &ldquo;meaning
space,&rdquo; where tokens used in similar ways land near each other.</p>
"""),
  ("diagram", EMBED_LOOKUP_SVG,
   "The lookup, drawn: an ID indexes the embedding table, and row #ID simply is the token's "
   "numbers (4 of 256 shown; values illustrative). The cell colours preview the heatmap below — "
   "similar words get similar rows."),
  ("diagram", EMBED_SCATTER_SVG,
   "Each token is its own point in 256-dimensional space (2 dimensions shown here); similar meanings "
   "cluster. The axes are two of the 256 learned attributes/dimensions — loosely, 'animal-ness' across "
   "and 'concreteness' up: touchable things high, actions in the middle, pure grammar words low "
   "(held lightly)."),
  ("diagram", EMBED_HEATMAP_SVG,
   "The same embeddings as colours: each row is a token, each column one of the 256 dimensions, each "
   "cell the token's value on it (red high, blue low). Similar tokens — fox, cat, dog — show similar "
   "patterns; \"the\" differs."),
  ("callout", "aside", "Attributes = dimensions", r"""
<p>A token's embedding is a point in <strong>256-dimensional space</strong>: 256 numbers, one per
dimension. Each dimension is a <strong>learned attribute (feature)</strong>: a mathematical abstraction
capturing some statistically-shared pattern across tokens. They <strong>don't map cleanly to human
concepts</strong>, but it's often genuinely helpful to imagine them, loosely, as fuzzy attributes —
&ldquo;animal-ness&rdquo;, &ldquo;furriness&rdquo;, &ldquo;size&rdquo; — held lightly. (A token's
<em>values</em> on the dimensions are part of the model's parameters; the dimensions themselves are the
embedding's axes.)</p>
"""),
  ("callout", "key", "Where do the embeddings come from?", r"""
<p>Not from the letters, and not computed on the fly: they're <strong>learned, then looked up</strong>.
The model keeps an <strong>embedding table</strong> (one row per vocabulary token). &ldquo;fox&rdquo;
becomes an integer ID, and that ID simply <em>indexes the table</em>; row #ID <em>is</em> its 256 numbers.
There's no arithmetic on <code>f-o-x</code>.</p>
<p>Those numbers start as <strong>small random values</strong> and are <strong>parameters</strong> like any
other: gradient descent nudges them, step by step, to lower the loss. After training the table is frozen, so
the lookup is deterministic (same token → same row), but the row was <em>learned</em>, not derived from the
spelling. (Train again with a different random seed and &ldquo;fox&rdquo; settles on a different,
equally-good vector.) Tokens used in similar contexts get pushed toward similar rows, which is exactly why
the clusters above emerge on their own, with no one labelling them.</p>
"""),
 ],
},

{
 "id": "linear", "num": "4", "title": "The linear layer (the core operation)",
 "blocks": [
  ("prose", r"""
<p>Almost the entire network is one operation, repeated: the <strong>linear layer</strong>,
<code>y = Wx + b</code>. It takes a vector of numbers in and produces a new vector out, where each output
is a <em>weighted sum</em> of all the inputs plus an offset. Stack the per-output weight-rows into a grid
<code>W</code> and the offsets into a vector <code>b</code>, and that's the whole layer: the school-line
<code>y = mx + c</code>, vectorised. The diagram below builds it from one output up to the whole model.</p>
"""),
  ("diagram", LINEAR_SVG,
   "A linear layer, drawn. ① one output (a \"neuron\") is a weighted sum of one token's numbers; ② stack "
   "a row of weights per output → the matrix W, so the layer is y = Wx + b (a vector in, a new vector "
   "out); ③ one such layer is a tiny slice of the whole ~3.24M-parameter model, whose weights are shared "
   "across every token."),
  ("callout", "key", "Parameters vs. tokens: the part people mix up", r"""
<p>A token doesn't <em>have</em> parameters. The parameters (every <code>W</code> and <code>b</code>)
<strong>are the model</strong>: fixed after training and <strong>shared</strong>, so the exact same
weights process every token, at every position. A token is just data flowing through them.</p>
<p>And the weights in the picture are a tiny slice: <em>one output of one layer</em>. Our tiny GPT stacks
4 blocks (each with several <code>W</code>s) plus the embedding and the head; add them all up and you get
the ~3.2M parameters. One layer's <code>W</code> might be 256×1024 (~262k numbers); the whole model is ~3.2M.</p>
<p>And a linear layer transforms <em>one token at a time</em>. The model's real job (read a <em>string</em>
of tokens and predict the next) needs tokens to share information, which is <em>attention</em>'s job
(next section), not the linear layers. After the stack, the last position's vector is read out to predict
the next token. <a href="../track-a/#block">Part 1 builds the block →</a></p>
"""),
 ],
},

{
 "id": "activation", "num": "5", "title": "The bend (activations)",
 "blocks": [
  ("prose", r"""
<p>Stacking linear layers alone is pointless: a stack of straight-line operations collapses into one
straight line, and the model could only ever draw <em>lines</em>. So after each linear step the model
applies one simple <strong>nonlinear</strong> function: a <em>bend</em>. That bend is what lets depth
model curves and combinations, not just proportions.</p>
<p>Ours is <strong>GELU</strong> (a smooth version of ReLU). The famous textbook ones are <strong>ReLU</strong>
(keep positives, zero the rest) and the <strong>sigmoid</strong> (squash any number into 0–1). The whole kit
is just this: <code>Wx + b</code>, then a bend, stacked — plus the two ideas below.</p>
"""),
 ],
},

{
 "id": "attention", "num": "6", "title": "Attention: letting tokens talk",
 "blocks": [
  ("prose", r"""
<p>Linear layers process each token on its own. But meaning depends on context: &ldquo;bank&rdquo; near
&ldquo;river&rdquo; vs near &ldquo;money.&rdquo; <strong>Attention</strong> is the one step where positions
<em>look at each other</em>: each token forms a query and asks &ldquo;which earlier tokens matter to me?&rdquo;,
then pulls in a blend of their information. It's how the model carries context forward, the part that makes
it a <em>language</em> model and not a bag of independent words.</p>
<p>And this isn't a metaphor — it's measurable. Here is the sentence from above, run through the
trained Part 1 model, with one attention head's actual weights drawn as arcs:</p>
"""),
  ("diagram", ATTENTION_SVG,
   "Attention, measured (not illustrated): when “it” builds its understanding, this head hands 76% "
   "of the blend to “dragon”. The thickness of each arc is the real weight from the trained model — "
   "the q·k matching from Part 1's formula, drawn."),
  ("callout", "aside", "Why it's the heart of it", r"""
<p>Everything else (embeddings, linear layers, the bend) works token-by-token. Attention is the <em>only</em>
place information moves <em>between</em> tokens. Stack several attention+MLP blocks and the model can build
up rich, context-aware meaning before it ever makes a prediction. <a href="../track-a/#attention">Part 1
builds attention →</a></p>
"""),
 ],
},

{
 "id": "learn", "num": "7", "title": "How it learns: loss, gradients, gradient descent",
 "part": "Learning", "part_banner": "Part 0 · How learning works",
 "blocks": [
  ("prose", r"""
<p>Where do the millions of parameters come from? <strong>Training.</strong> Show the model real text with
the next token hidden, let it guess, and measure how wrong the guess was with a single number: the
<strong>loss</strong> (low = confident and right; high = wrong). Training is nothing more than making that
number smaller, over and over.</p>
<p>The trick is knowing <em>which way</em> to nudge each of the millions of parameters. That's the
<strong>gradient</strong>: for every parameter, the slope of the loss, telling you which direction, and how hard,
reduces the error. Nudge every parameter a little down its slope, and the loss drops. Do it a few thousand
times and coherent language emerges. This is <strong>gradient descent</strong>.</p>
"""),
  ("diagram", LANDSCAPE_SVG,
   "Gradient descent with ONE weight: picture the loss as a curve and the model as a ball. The "
   "gradient is the downhill direction; each training step rolls the ball one step lower."),
  ("diagram", SURFACE3D_SVG,
   "Now with TWO weights the loss becomes a landscape, and the dotted line is a real gradient-descent "
   "run on this very surface: at every step, feel the slope, step downhill. Our model has millions of "
   "weights — a landscape in millions of dimensions — but the move never changes."),
  ("prose", r"""
<p>One pass of training is a loop of four steps, repeated on batch after batch of text:</p>
"""),
  ("diagram", CYCLE_SVG,
   "The training loop: a forward pass (guess the next tokens) → compute the loss (how wrong) → a backward "
   "pass (backpropagation: work the slopes back through every layer to get each parameter's gradient) → "
   "update (nudge every parameter a little downhill). Then repeat."),
  ("callout", "aside", "Backpropagation, in one line", r"""
<p>The <strong>backward pass</strong> (&ldquo;backprop&rdquo;) is just the chain rule from calculus run at
scale: starting from the loss, it works the slopes backward through every layer to find each parameter's
gradient efficiently. It's the engine that makes training millions of parameters feasible.
<a href="../track-a/#train">Part 1 runs the training loop →</a></p>
"""),
 ],
},

{
 "id": "generate", "num": "8", "title": "Generating text, and the one knob: temperature",
 "blocks": [
  ("prose", r"""
<p>Once trained, the model <em>generates</em> by running its prediction in a loop: feed the text so far,
get a probability for every next token, pick one, append it, repeat. &ldquo;Inference&rdquo; and
&ldquo;generation&rdquo; are the same thing: running the function forward (no learning).</p>
<p>How you <em>pick</em> from the probabilities is the one knob worth feeling: <strong>temperature</strong>.
Low temperature (~0.5) almost always grabs the most likely token: safe, repetitive. High (~1.1) samples more
adventurously: varied, riskier, sometimes incoherent. It's the dial between &ldquo;careful&rdquo; and
&ldquo;creative,&rdquo; and it changes nothing in the model — only how its output is sampled.
<a href="../track-a/#temperature">Part 1 lets you feel it →</a></p>
"""),
  ("diagram", TEMP_SVG,
   "Temperature, measured on the real model: the same scores sampled two ways. Low temperature "
   "concentrates the draws on the favourite; high temperature hands nearly half of them to the "
   "long tail of everything else."),
 ],
},

{
 "id": "ceiling", "num": "9", "title": "The honest ceiling, and where this goes",
 "blocks": [
  ("prose", r"""
<p>That's the whole machine: text → tokens → embeddings → stacks of (attention + <code>Wx+b</code> + a bend)
→ a final prediction, all tuned by gradient descent. A <em>frontier</em> model is exactly this, scaled up:
more dimensions, more layers, vastly more text and compute. Same ideas; different magnitude.</p>
<p>A from-scratch tiny model trained on a laptop will produce believable <em>shapes</em> of language but no
real knowledge — that's the honest ceiling, and it's the point: you can see every moving part. To get
something <em>useful</em>, you start from a model that has already paid the scale cost and
<strong>specialise</strong> it, which is Part 2.</p>
"""),
  ("callout", "key", "Now see it built", r"""
<p>Every idea here is built in real, runnable code next: <strong><a href="../track-a/">Part 1 ·
Pre-training</a></strong> trains this tiny GPT from scratch, one piece at a time. Then
<strong><a href="../track-b/">Part 2 · Post-training</a></strong> fine-tunes a real open model into a
useful clinical-trial expert, the same concepts doing a real job. ← back to
<a href="../">the lab home</a>.</p>
"""),
 ],
},

]
